name: StairSeatDown
main: StairSeatDown\Main
author: gamesukimanIRS
authors: ["maru(Produser dari jenis plug-in ini)","DusKong(Saya menerima kode sampel terkait paket)"]
version: "1.0.0"
api:
- 3.0.0
- 3.0.0-ALPHA9
- 4.0.0
